### ISSUE TITLE
Serializer should be instancialized only within BaseResource creation

### ISSUE THREAD

**Issue by igortg** [ESSS/flask-restalchemy#30]
Currently, serializers are instancialized in the model registartion (`add_model`, `add_relationship`).

This requires that `register_column_serializer` to be called before any mode registration, which is a burden for those that want to customize field serializers.

**Comment by lincrosenbach** [comment]
@igortg I believe the following PR solve this, right? 
https://github.com/ESSS/serialchemy/pull/6

**Comment by igortg** [comment]
yup, thks
